name: pipeline
on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Package
      run: mvn package

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          package: '*jar'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-dev:
    needs: publish
    runs-on: ubuntu-latest
    environment:
      name: DEV
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy
        shell: bash
        run:
          echo "Deploy DEV"

  Smoketest:
    needs: deploy-dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
        name: Deploy
        shell: bash
        run:
          sh 'src/main/scripts/smoketest.sh'
    
  deploy-Pre:
    needs: publish
    runs-on: ubuntu-latest
    environment:
      name: PRE
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Deploy
        shell: bash
        run:
          echo "Deploy PRE"

  deploy-prd:
    needs: publish
    runs-on: ubuntu-latest
    environment:
      name: PRD
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
        shell: bash
        run:
          echo "Deploy PRD"
