name: pipeline
on: 
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    -  uses: actions/checkout@v3
       with:
         fetch-depth: 0
    - run: mvn test
    
    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2.0.1
    
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco/
  
  build:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Package
      run: mvn package
      
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          package: '*jar'
      - name: Publish package
        #run: mvn --batch-mode deploy
        run: 
          echo "Run publish fake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-DEV:
    needs: publish
    runs-on: ubuntu-latest
    environment:
      name: DEV
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy
        shell: bash
        run:
          echo "Deploy DEV"

  Smoketest-DEV:
    needs: deploy-DEV
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        shell: bash
        run:
          sh 'src/main/scripts/smoketest.sh'
          
  TestesFuncionais:
    needs: Smoketest-DEV
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        shell: bash
        run:
          sh 'src/main/scripts/testesFuncionais.sh'
    
  deploy-PRE:
    needs: publish
    runs-on: ubuntu-latest
    environment:
      name: PRE
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Deploy
        shell: bash
        run:
          echo "Deploy PRE"
          
  Smoketest-PRE:
    needs: deploy-PRE
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        shell: bash
        run:
          sh 'src/main/scripts/smoketest.sh'

  TesteIntegrado-PRE:
    needs: Smoketest-PRE
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        shell: bash
        run:
          sh 'src/main/scripts/testeIntegrado.sh'

  deploy-PRD:
    needs: publish
    runs-on: ubuntu-latest
    environment:
      name: PRD
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
        shell: bash
        run:
          echo "Deploy PRD"

  Smoketest-PRD:
    needs: deploy-PRD
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        shell: bash
        run:
          sh 'src/main/scripts/smoketest.sh'
