name: Teste Variavel de ambiente
on:
  push: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run
      run: echo 
      env:
        var: ${{ secrets.var }}
