name: Teste Variavel de ambiente
on:
  push: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Print secret
    - shell: bash
      env:
        var: ${{ secrets.var }}
      run: |
        echo "$var"
